var html = '<!-- サイドメニューここから -->';
html += ' <nav>';
html += ' 	<div class="inner">';
html += ' 		<ul class="gnav">';
html += ' 			<li><a href="index.html">TOP</a>';
html += ' 			</li>';
html += ' 			<li class="subnav"><a href="event.html">イベント</a>';
html += ' 				<ul>';
html += ' 					<li><a href="event.html?id=event">イベントステージ</a></li>';
html += ' 					<li><a href="event.html?id=gym">体育館行事</a></li>';
html += ' 				</ul>';
html += ' 			</li>';
html += '             <li class="subnav"><a href="panten.html">一般展示</a>';
html += ' 				<ul>';
html += ' 					<li><a href="panten.html?id=1">1階</a></li>';
html += ' 					<li><a href="panten.html?id=2">2階</a></li>';
html += ' 					<li><a href="panten.html?id=3">3階</a></li>';
html += ' 				</ul>';
html += ' 			</li>';
html += ' 			<li><a href="goods.html">グッズ</a></li>';
html += ' 			<li class="subnav"><a href="food.html">食べ物</a>';
html += ' 				<ul>';
html += ' 					<li><a href="food.html?id=m">模擬店</a></li>';
html += ' 					<li><a href="food.html?id=s">食堂</a></li>';
html += ' 					<li><a href="food.html?id=k">喫茶店</a></li>';
html += ' 				</ul>';
html += ' 			</li>';
html += ' 			<li class="subnav"><a href="access.html">アクセス</a>';
html += ' 				<ul>';
html += ' 					<li><a href="access.html?id=shuttle">シャトルバス</a></li>';
html += ' 					<li><a href="access.html?id=parking">駐車場</a></li>';
html += ' 				</ul>';
html += ' 			</li>';
html += ' 			<li><a href="movie.html">動画</a></li>';
html += ' 			<li class="subnav"><a href="radio.html">ラジオ</a>';
html += ' 				<ul>';
html += ' 					<li><a href="radio.html?id=form">投稿フォーム</a></li>';
html += ' 				</ul>';
html += ' 			</li>';
html += ' 			<li><a href="form.html">お問い合わせ</a></li>';
html += ' 		</ul>';
html += ' 	</div><!-- /.inner -->';
html += ' </nav>';
document.write(html); 